@baseUrl = http://localhost:5000
@adminToken = admin_token
@routeId = route_id

### Create Stop With Nominatim
POST {{baseUrl}}/api/stops
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Main Library Stop",
  "code": "MLS-07",
  "route": "{{routeId}}",
  "order": 5,
  "locationName": "Gate 1",
  "address": "The British University in Egypt, El Shorouk, Cairo, Egypt",
  "isActive": true
}